"""
Django settings for core project.
Generated by 'django-admin startproject' using Django 6.0.2.
For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import ipaddress
import dj_database_url
from pathlib import Path
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-dev-key-for-local-testing')

# SECURITY WARNING: don't run with debug turned on in production!
IS_PRODUCTION = os.environ.get('VERCEL_ENV') == 'production'
if IS_PRODUCTION:
    DEBUG = False
else:
    DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = ['.vercel.app']

if DEBUG or not IS_PRODUCTION:
    ALLOWED_HOSTS.extend(['localhost', '127.0.0.1'])

# Add extra domains from ALLOWED_HOSTS_EXTRA environment variable
extra_hosts = [host.strip() for host in os.environ.get('ALLOWED_HOSTS_EXTRA', '').split(',') if host.strip()]
if '*' in extra_hosts:
    raise ImproperlyConfigured("ALLOWED_HOSTS_EXTRA must not contain '*'")
ALLOWED_HOSTS.extend(extra_hosts)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'game',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
WHITENOISE_USE_FINDERS = True

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Cache configuration
# In production, we require a shared cache backend (e.g., DatabaseCache
# or Redis). LocMemCache is per-process and can bypass login lockouts
# in multi-worker environments.
cache_backend = os.environ.get(
    'CACHE_BACKEND',
    'django.core.cache.backends.db.DatabaseCache' if IS_PRODUCTION
    else 'django.core.cache.backends.locmem.LocMemCache'
)

if IS_PRODUCTION and 'locmem.LocMemCache' in cache_backend:
    raise ImproperlyConfigured(
        "LocMemCache cannot be used in production because it is "
        "per-process and not shared across workers. Please configure "
        "a shared backend like Redis or DatabaseCache."
    )

CACHES = {
    'default': {
        'BACKEND': cache_backend,
        'LOCATION': os.environ.get(
            'CACHE_LOCATION',
            'checkora_cache_table' if IS_PRODUCTION else 'checkora-cache'
        ),
    }
}


PASSWORD_RESET_EMAIL_COOLDOWN_SECONDS = 300
PASSWORD_RESET_IP_WINDOW_SECONDS = 900
PASSWORD_RESET_IP_MAX_REQUESTS = 3

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "game" / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Session and CSRF cookie security (production only — local runserver is HTTP).
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = IS_PRODUCTION
SESSION_COOKIE_SAMESITE = 'Lax'

CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = IS_PRODUCTION
CSRF_COOKIE_SAMESITE = 'Lax'

# SSL redirect and HSTS only on Vercel; avoids local HTTP→HTTPS redirect loops.
SECURE_SSL_REDIRECT = IS_PRODUCTION
if IS_PRODUCTION:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Email Configuration for OTP and Password Reset Emails
if DEBUG:
    _DEFAULT_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    _DEFAULT_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Env var override must still win, explicit .env value takes priority
# Fixed: Using 'or' ensures that empty string values in .env fall back safely to _DEFAULT_BACKEND
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND') or _DEFAULT_BACKEND

# DO NOT TOUCH - Keep remaining settings exactly as they were originally
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL') or EMAIL_HOST_USER


# Redirect after login
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'landing'

# Password reset link expiration (5 minutes)
PASSWORD_RESET_TIMEOUT = 300

# SECURITY SETTINGS (Implemented via GSSoC Audit)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_SECONDS = 31536000 if IS_PRODUCTION else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = IS_PRODUCTION
SECURE_HSTS_PRELOAD = IS_PRODUCTION

# Secret token for authenticating Vercel cron job requests to /api/cron/cleanup-stale-games/
CRON_SECRET = os.environ.get('CRON_SECRET')

# Trusted proxies for client IP extraction from X-Forwarded-For header
TRUSTED_PROXIES = os.environ.get('TRUSTED_PROXIES', '127.0.0.1,::1').split(',')
TRUSTED_PROXIES = [ip.strip() for ip in TRUSTED_PROXIES if ip.strip()]

# Trusted proxies for password reset rate limiting client IP extraction
_trusted_proxy_ips_raw = [
    ip.strip()
    for ip in os.environ.get('TRUSTED_PROXY_IPS', '').split(',')
    if ip.strip()
]

TRUSTED_PROXY_IPS = []
_invalid_trusted_proxy_ips = []
for entry in _trusted_proxy_ips_raw:
    try:
        ipaddress.ip_network(entry, strict=False)
    except ValueError:
        _invalid_trusted_proxy_ips.append(entry)
    else:
        TRUSTED_PROXY_IPS.append(entry)

if _invalid_trusted_proxy_ips:
    raise ImproperlyConfigured(
        "TRUSTED_PROXY_IPS contains invalid IP/CIDR values: "
        + ", ".join(_invalid_trusted_proxy_ips)
    )

if IS_PRODUCTION and not TRUSTED_PROXY_IPS:
    raise ImproperlyConfigured(
        'TRUSTED_PROXY_IPS must be set in production'
    )



