# Generated by Django 6.0.5 on 2026-06-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_puzzlestats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puzzlestats",
            name="best_streak",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="puzzlestats",
            name="puzzles_solved",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
