# Generated by Django 6.0.5 on 2026-06-02 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_alter_puzzlestats_best_streak_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="puzzlestats",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="puzzle_stats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="puzzlestats",
            constraint=models.CheckConstraint(
                condition=models.Q(("best_streak__gte", models.F("current_streak"))),
                name="best_streak_gte_current_streak",
            ),
        ),
    ]
