# Generated by Django 6.0.5 on 2026-06-04 05:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0009_lessonprogress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lessonprogress",
            unique_together={("user", "lesson_name")},
        ),
    ]
