# Generated by Django 6.0.5 on 2026-06-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0010_alter_lessonprogress_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonprogress",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
