# Generated by Django 6.0.5 on 2026-06-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0012_achievement_userachievement"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="category",
            field=models.CharField(
                choices=[
                    ("gameplay", "Gameplay"),
                    ("puzzle", "Puzzle"),
                    ("lessons", "Lessons"),
                    ("streaks", "Streaks"),
                    ("special", "Special Achievements"),
                ],
                default="gameplay",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="rarity",
            field=models.CharField(
                choices=[
                    ("common", "Common"),
                    ("rare", "Rare"),
                    ("epic", "Epic"),
                    ("legendary", "Legendary"),
                ],
                default="common",
                max_length=20,
            ),
        ),
    ]
