# Generated by Django 6.0.5 on 2026-06-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0015_userprogress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprogress",
            name="level",
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="xp",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
