# Generated by Django 6.0.5 on 2026-06-10 12:29

from django.db import migrations, models


def seed_puzzles(apps, schema_editor):
    ChessPuzzle = apps.get_model('game', 'ChessPuzzle')
    initial_puzzles = [
        {
            "title": "Daily Puzzle #1",
            "fen": "6k1/5ppp/8/8/8/8/5PPP/6KQ w - - 0 1",
            "solution": ["g2g4"],
            "difficulty": "easy"
        },
        {
            "title": "Daily Puzzle #2",
            "fen": "7k/5K2/6Q1/8/8/8/8/8 w - - 0 1",
            "solution": ["g6g7"],
            "difficulty": "easy"
        },
        {
            "title": "Daily Puzzle #3",
            "fen": "6k1/5ppp/8/8/8/8/5PPP/5RK1 w - - 0 1",
            "solution": ["f1e1"],
            "difficulty": "easy"
        },
        {
            "title": "Daily Puzzle #4",
            "fen": "6k1/5ppp/8/8/8/8/5PPP/5QK1 w - - 0 1",
            "solution": ["f1h7"],
            "difficulty": "medium"
        },
        {
            "title": "Daily Puzzle #5",
            "fen": "7k/6pp/8/8/8/8/5PPP/6KQ w - - 0 1",
            "solution": ["h1h7"],
            "difficulty": "medium"
        },
        {
            "title": "Daily Puzzle #6",
            "fen": "7k/5K2/7Q/8/8/8/8/8 w - - 0 1",
            "solution": ["h6g7"],
            "difficulty": "medium"
        },
        {
            "title": "Daily Puzzle #7",
            "fen": "6k1/5ppp/8/8/8/8/6PP/5RK1 w - - 0 1",
            "solution": ["f1e1"],
            "difficulty": "easy"
        },
    ]
    for p in initial_puzzles:
        ChessPuzzle.objects.get_or_create(
            fen=p["fen"],
            defaults={
                "title": p["title"],
                "solution": p["solution"],
                "difficulty": p["difficulty"],
            }
        )


def reverse_seed_puzzles(apps, schema_editor):
    ChessPuzzle = apps.get_model('game', 'ChessPuzzle')
    ChessPuzzle.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_playerrating_games_played_matches_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessPuzzle',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('title', models.CharField(max_length=200)),
                ('fen', models.CharField(max_length=255)),
                ('solution', models.JSONField(
                    help_text=(
                        "JSON array of moves representing the solution, "
                        "e.g. ['g2g4']"
                    )
                )),
                ('difficulty', models.CharField(
                    blank=True,
                    choices=[
                        ('easy', 'Easy'),
                        ('medium', 'Medium'),
                        ('hard', 'Hard')
                    ],
                    default='',
                    max_length=20
                )),
                ('date', models.DateField(
                    blank=True,
                    db_index=True,
                    help_text='Date when this puzzle should be served',
                    null=True,
                    unique=True
                )),
            ],
        ),
        migrations.RunPython(seed_puzzles, reverse_seed_puzzles),
    ]
