# Generated by Django 6.0.5 on 2026-06-18 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0020_discussion_reply"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OpeningProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opening_name", models.CharField(max_length=100)),
                ("openings_started", models.PositiveIntegerField(default=0)),
                ("openings_completed", models.PositiveIntegerField(default=0)),
                ("correct_moves", models.PositiveIntegerField(default=0)),
                ("incorrect_moves", models.PositiveIntegerField(default=0)),
                ("last_checkpoint", models.PositiveIntegerField(default=0)),
                ("completion_percentage", models.FloatField(default=0)),
                ("accuracy_percentage", models.FloatField(default=0)),
                ("last_practiced", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "opening_name")},
            },
        ),
    ]
