# Generated by Django 6.0.5 on 2026-06-18 13:56

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0021_openingprogress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="openingprogress",
            name="accuracy_percentage",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="openingprogress",
            name="completion_percentage",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="openingprogress",
            index=models.Index(
                fields=["user", "openings_completed"],
                name="game_openin_user_id_0f5d10_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="openingprogress",
            index=models.Index(
                fields=["user", "openings_started"],
                name="game_openin_user_id_edeb0a_idx",
            ),
        ),
    ]
