# Generated by Django 6.0.5 on 2026-06-18 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_reply_is_deleted_reply_is_edited_reply_reply_to_and_more'),
        ('game', '0022_alter_openingprogress_accuracy_percentage_and_more'),
    ]

    operations = [
    ]
