# Generated by Django 6.0 on 2026-06-26 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0026_activegame"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activegame",
            name="game_state",
        ),
    ]
