# Generated by Django 5.2.15 on 2026-06-24 11:13

from django.db import migrations
from django.conf import settings


def backfill_profiles(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    UserProfile = apps.get_model('game', 'UserProfile')
    
    # Create profiles for all users that don't have one
    existing_profile_user_ids = UserProfile.objects.values_list('user_id', flat=True)
    users_without_profiles = User.objects.exclude(id__in=existing_profile_user_ids)
    
    profiles_to_create = [UserProfile(user=user) for user in users_without_profiles]
    UserProfile.objects.bulk_create(profiles_to_create, ignore_conflicts=True)

def reverse_backfill(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_userprofile'),
    ]

    operations = [
        migrations.RunPython(backfill_profiles, reverse_backfill),
    ]
