# Generated by Django 6.0 on 2026-06-27 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0027_backfill_user_profiles"),
        ("game", "0027_remove_activegame_game_state"),
    ]

    operations = []
