# Generated by Django 6.0 on 2026-06-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0028_merge_20260627_1144"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activegame",
            name="session_key",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
