# Generated by Django 6.0 on 2026-06-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0029_alter_activegame_session_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activegame",
            name="last_active",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
