# Generated by Django 6.0 on 2026-06-27 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0030_alter_activegame_last_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="activegame",
            index=models.Index(
                fields=["status", "last_active"], name="game_active_status_22ef23_idx"
            ),
        ),
    ]
